version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-rocketpass_development}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  web:
    build:
      context: .
      args:
        RUBY_VERSION: 3.3.5
    environment:
      RAILS_ENV: ${RAILS_ENV:-production}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-rocketpass_development}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      # Active Storage service selection (production.rb defaults to :local)
      # ACTIVE_STORAGE_SERVICE: amazon
      # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_S3_BUCKET
    depends_on:
      - db
      - redis
    ports:
      - "3000:80"

  sidekiq:
    build:
      context: .
      args:
        RUBY_VERSION: 3.3.5
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      RAILS_ENV: ${RAILS_ENV:-production}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-rocketpass_development}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - db
      - redis

volumes:
  db-data:
  redis-data:

